### ISSUE TITLE
paste as plain text does not handle inline - elements properly

### ISSUE THREAD

**Issue by bwl21** [jinhofer/pastespecial#9]
When I paste 

```html
<p><span>This is <b>bold</b> text</span>
</p>
````
as unformatted text, I get
````
html
<p><span><p>This is&nbsp;</p><p>bold</p>&nbsp;text<p></p><p><br></p><br></span>
</p>
```

but it should be
```html
<p>this is bold text</p>
```

**Comment by jinhofer** [comment]
Thank you for opening a separate ticket for this! I fixed this when you brought it up in our other ticket, and will close this ticket when I release a new version.

**Comment by jinhofer** [comment]
I have released a new version on Moodle that includes this fix!

**Comment by bwl21** [comment]
I tested this, but behavior is still not fully ok.

```html
<p>das ist <b>bold</b> text</p>
```

now yields

```html
<p>das ist&nbsp;bold&nbsp;text</p>
```

It appears that it still surrounds inline elements with &nbsp;

There is one more thing I have reported in https://github.com/jinhofer/pastespecial/issues/11

**Comment by jinhofer** [comment]
I tried to recreate this after the update, and I am seeing the result as:
<p>das ist bold text</p>

Did you make sure that the plugin was updated and the caches were cleared?

**Comment by bwl21** [comment]
this is what it looks in the WYSIWYG. But if yo inspect the pure HTML you see that there are &nbsp;

**Comment by jinhofer** [comment]
Here's my HTML:
![image](https://cloud.githubusercontent.com/assets/8837519/12628022/bee6d55e-c506-11e5-8939-2cf0f60104ec.png)

**Comment by bwl21** [comment]
I investigated it again. Amazingly, now I also do not have the &nbsp; Sorry.

**Comment by jinhofer** [comment]
That seems to happen to me occasionally as well. I think it has something to do with caches, because now that it does work the way we want, it won't go back to the issue that you were finding. If it DOES, though, then that's definitely an issue.
